# 禁用定制插件
#safe: false
# 在发布文章时使用一个未来的日期
future: true
# 产生相关页面的索引
#lsi: false

# 使用指定的基准网址来运行网站
#baseurl: /
# 改变Jekyll服务的端口
#port: 4000
# 设置站点的网址，这对环境改变时很有用
url: http://localhost:4000
# url: http://idxuan.github.io

title: 老轩的博客
description: 老轩的生活点滴
disqus_shortname: idxuan

# Owner/author information
owner:
    name: 老轩
    avatar: avatar.jpg
    bio: "~~晒高楼的阳光~~ ~~吻唇角的残鬓~~ ~~弹易断的琴弦~~ ~~饮不醒的美酒~~"
    email: idxuan@hotmail.com
    # Social networking links used in footer. Update and remove as you like.
    github: idxuan
    twitter:
    facebook:
    stackexchange:
    linkedin:
    instagram:
    flickr:
    tumblr:
    # For Google Authorship https://plus.google.com/authorship
    google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
    - title: FEED
      url: /feed.xml
      external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#timezone: Asia/Shanghai
highlighter: pygments
#markdown: redcarpet
#markdown: rdiscount
markdown: kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink: /:categories/:year/:month/:day/:title
permalink: /blog/:year/:month/:day/:title

# Amount of post to show on home page
paginate: 5

kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    use_coderay: true

    coderay:
        coderay_line_numbers: nil
        coderay_line_numbers_start: 1
        coderay_tab_width: 4
        coderay_bold_every: 10
        coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
